name: argscape
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - tskit
  - msprime
  - numpy>=1.24.0,<2.0.0
  - fastapi
  - uvicorn
  - python-multipart
  - pandas==2.0.3
  - scikit-learn
  - geopandas
  - pydantic
  - apscheduler
  - pyproj
  - shapely
  - pip
  - pip:
    - tszip
    - tsdate
    - fastgaia
    - geoancestry
