[build]
builder = "nixpacks"
buildCommand = "pip install -e backend/"

[deploy]
startCommand = "cd backend && python startup.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 