export const LINE_WIDTHS = {
    NODE_OUTLINE_SELECTED: 2,
    NODE_OUTLINE_ROOT: 1.5,
    NODE_OUTLINE_SAMPLE: 0.8,
    MIN_NODE_OUTLINE: 0.3,
    MAX_NODE_OUTLINE: 4,
    GEOGRAPHIC_ACTIVE: 2,
    GEOGRAPHIC_NORMAL: 1,
    TIME_SLICE_ACTIVE: 2,
    TIME_SLICE_NORMAL: 1
  } as const;