export const VISUALIZATION_CONSTANTS = {
    DEFAULT_ZOOM: 2.5,
    AUTO_FIT_ZOOM: 1.8,
    JITTER_SCALE: 0.001,
    JITTER_RANGE: 0.02,
    JITTER_OFFSET: 0.01,
    GEOGRAPHIC_OPACITY_SCALE: 2.5,
    GEOGRAPHIC_REDUCED_OPACITY: 0.3,
    TEMPORAL_OPACITY_SCALE: 0.3,
    GRID_EXTENSION: 2,
    NODE_OPACITY: 0.85,
    BASE_ELEVATION: 0.1,
    SELECTED_NODE_SCALE: 1.5,
    TEMPORAL_FADE_OPACITY: 0.3,
    EDGE_FADE_OPACITY: 0.15,
    EDGE_PARTIAL_FADE_OPACITY: 0.35,
    REDUCED_OPACITY_MULTIPLIER: 0.2,
    UNIT_GRID_SIZE: 10,
}

// Constants (Diff)
export const VISUALIZATION_CONSTANTS_DIFF = {
    DEFAULT_ZOOM: VISUALIZATION_CONSTANTS.DEFAULT_ZOOM,
    AUTO_FIT_ZOOM: VISUALIZATION_CONSTANTS.AUTO_FIT_ZOOM,
    JITTER_SCALE: VISUALIZATION_CONSTANTS.JITTER_SCALE, 
    JITTER_RANGE: VISUALIZATION_CONSTANTS.JITTER_RANGE,   
    JITTER_OFFSET: VISUALIZATION_CONSTANTS.JITTER_OFFSET,  
    GEOGRAPHIC_OPACITY_SCALE: VISUALIZATION_CONSTANTS.GEOGRAPHIC_OPACITY_SCALE,
    GEOGRAPHIC_REDUCED_OPACITY: VISUALIZATION_CONSTANTS.GEOGRAPHIC_REDUCED_OPACITY,
    TEMPORAL_OPACITY_SCALE: VISUALIZATION_CONSTANTS.TEMPORAL_OPACITY_SCALE,
    GRID_EXTENSION: VISUALIZATION_CONSTANTS.GRID_EXTENSION,
    NODE_OPACITY: VISUALIZATION_CONSTANTS.NODE_OPACITY,
    BASE_ELEVATION: VISUALIZATION_CONSTANTS.BASE_ELEVATION,
    SELECTED_NODE_SCALE: VISUALIZATION_CONSTANTS.SELECTED_NODE_SCALE,
    TEMPORAL_FADE_OPACITY: VISUALIZATION_CONSTANTS.TEMPORAL_FADE_OPACITY,
    EDGE_FADE_OPACITY: VISUALIZATION_CONSTANTS.EDGE_FADE_OPACITY,
    EDGE_PARTIAL_FADE_OPACITY: VISUALIZATION_CONSTANTS.EDGE_PARTIAL_FADE_OPACITY,
    REDUCED_OPACITY_MULTIPLIER: VISUALIZATION_CONSTANTS.REDUCED_OPACITY_MULTIPLIER,
    UNIT_GRID_SIZE: VISUALIZATION_CONSTANTS.UNIT_GRID_SIZE, 
    MIN_ZOOM: 0.01,
    MAX_ZOOM: 50,
  } as const;

  // Constants (Regular)
export const VISUALIZATION_CONSTANTS_REG = {
    DEFAULT_ZOOM: VISUALIZATION_CONSTANTS.DEFAULT_ZOOM,
    AUTO_FIT_ZOOM: VISUALIZATION_CONSTANTS.AUTO_FIT_ZOOM,
    JITTER_SCALE: VISUALIZATION_CONSTANTS.JITTER_SCALE,
    JITTER_RANGE: VISUALIZATION_CONSTANTS.JITTER_RANGE,
    JITTER_OFFSET: VISUALIZATION_CONSTANTS.JITTER_OFFSET,
    GEOGRAPHIC_OPACITY_SCALE: VISUALIZATION_CONSTANTS.GEOGRAPHIC_OPACITY_SCALE,
    GEOGRAPHIC_REDUCED_OPACITY: VISUALIZATION_CONSTANTS.GEOGRAPHIC_REDUCED_OPACITY,
    TEMPORAL_OPACITY_SCALE: VISUALIZATION_CONSTANTS.TEMPORAL_OPACITY_SCALE,
    GRID_EXTENSION: VISUALIZATION_CONSTANTS.GRID_EXTENSION,
    NODE_OPACITY: VISUALIZATION_CONSTANTS.NODE_OPACITY,
    BASE_ELEVATION: VISUALIZATION_CONSTANTS.BASE_ELEVATION,
    SELECTED_NODE_SCALE: VISUALIZATION_CONSTANTS.SELECTED_NODE_SCALE,
    TEMPORAL_FADE_OPACITY: VISUALIZATION_CONSTANTS.TEMPORAL_FADE_OPACITY,
    EDGE_FADE_OPACITY: VISUALIZATION_CONSTANTS.EDGE_FADE_OPACITY,
    EDGE_PARTIAL_FADE_OPACITY: VISUALIZATION_CONSTANTS.EDGE_PARTIAL_FADE_OPACITY,
    REDUCED_OPACITY_MULTIPLIER: VISUALIZATION_CONSTANTS.REDUCED_OPACITY_MULTIPLIER,
    UNIT_GRID_SIZE: VISUALIZATION_CONSTANTS.UNIT_GRID_SIZE,
    BASE_MIN_ZOOM: 0.001, // Much lower minimum for extreme deep z-axis navigation
    BASE_MAX_ZOOM: 500, // Much higher base maximum for better z-axis reach
    ZOOM_SCALE_FACTOR: 1.0, // Significantly increased factor for aggressive z-axis navigation
  } as const;